### ISSUE TITLE
Add selectors

### ISSUE THREAD

**Issue by dshaplyko** [scolt/travel-notes#13]
Please add selectors for the following items:
- Logout button
- Sign Up button (login page)
- Sign In button (registration page)
- Sorting toggle (My/All notes) on main page
- Please double check fields on Registration page (especially fields for uploading an image)
- Get Started button on the home page

**Comment by scolt** [comment]
* `#logoutMenuButton`
* `.login-footer a`
* `.logout-footer a`
* `#onlyMyButton`
* `#avatarDropzoneContainer input` , `#backgroundDropzoneContainer input`
* `#getStarted`
