### ISSUE TITLE
Add class names for Sorting elements

### ISSUE THREAD

**Issue by dshaplyko** [scolt/travel-notes#2]
Please add a nice readable class names Sorting elements
![2017-02-27 22 07 58](https://cloud.githubusercontent.com/assets/4024495/23375406/5163a6ee-fd39-11e6-854e-23914228c016.png)

**Comment by scolt** [comment]
<MenuItem id="orderByTitle" key={1} value={'title'} primaryText="Title" />
<MenuItem id="orderByUsername" key={2} value={'username'} primaryText="User" />
<MenuItem id="orderByDate" key={3} value={'created'} primaryText="Date" />
